services:
  # Redis service
  redis:
    image: redis:latest
    container_name: qik_url_api_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass 1234
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=qik-url-firestore-emulator
      - PORT=8200
    ports:
      - 8200:8200
volumes:
    redis_data:

  # app:
  #   image: your-app-image
  #   environment:
  #     - FIRESTORE_EMULATOR_HOST=firestore_emulator:8200
  #     - FIRESTORE_PROJECT_ID=qik_url_firestore_emulator
  # depends_on:
  #   - firestore_emulator

